# Generated by Django 2.1.5 on 2019-02-23 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
