# Generated by Django 2.1.5 on 2019-03-04 23:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_thumbnail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='media',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=products.models.thumbnail_location, width_field='width'),
        ),
    ]
