# Generated by Django 2.1.5 on 2019-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
